// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticDto = { severity: string, kind: string, section: string, field: string | null, offset: number | null, message: string, };
