// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveStringDto } from "./SaveStringDto";

export type HeaderDto = { mapName: SaveStringDto, mapFilename: SaveStringDto, mapDescription: SaveStringDto, width: number, height: number, difficulty: string, language: string, gameType: string, requiresPol: boolean, };
