// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticDto } from "./DiagnosticDto";
import type { SaveSummaryDto } from "./SaveSummaryDto";

export type LibrarySaveEntryDto = { path: string, fileName: string, sizeBytes: bigint, modifiedTimestamp: bigint | null, status: string, summary: SaveSummaryDto | null, diagnostics: Array<DiagnosticDto>, };
