// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticDto } from "./DiagnosticDto";
import type { HeaderDto } from "./HeaderDto";
import type { SourceDto } from "./SourceDto";

export type OpenedSaveDto = { source: SourceDto, header: HeaderDto, diagnostics: Array<DiagnosticDto>, };
