// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveStringDto = { text: string, rawBytes: Array<number>, validUtf8: boolean, modified: boolean, };
