// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveStringDto } from "./SaveStringDto";

export type SaveSummaryDto = { saveVersion: number, mapName: SaveStringDto, mapFileName: SaveStringDto, width: number, height: number, difficulty: string, gameMode: string, requiresPol: boolean, };
