// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioDto } from "./ScenarioDto";
import type { ValidationResultDto } from "./ValidationResultDto";

export type ScenarioMutationResultDto = { scenario: ScenarioDto, dirty: boolean, revision: bigint, validation: ValidationResultDto, };
